export const brokerFirmAddressMock = {
  id: '1234',
  firmId: 'test',
  addressType: 'Firm Address',
  numberOrBuilding: '5',
  postcode: 12345,
  city: 'Barcelona',
  country: 'Spain',
  lineOne: 'line 1',
  lineTwo: 'line 2',
  lineThree: 'line 3',
  lineFour: 'line 4',
  lineFive: 'line 5',
  tradingName: 'trading',
  businessDevelopmentManager: 'ni idea',
  isActive: true,
  lastUpdated: '2021-11-10T10:28:13.868Z',
  version: 0,
};
