export * from './address.service';
import { AddressService } from './address.service';
export * from './calculation.service';
import { CalculationService } from './calculation.service';
export * from './case.service';
import { CaseService } from './case.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './dIP.service';
import { DIPService } from './dIP.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './fMA.service';
import { FMAService } from './fMA.service';
export * from './firm.service';
import { FirmService } from './firm.service';
export * from './illustration.service';
import { IllustrationService } from './illustration.service';
export * from './intermediary.service';
import { IntermediaryService } from './intermediary.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './portalUser.service';
import { PortalUserService } from './portalUser.service';
export * from './product.service';
import { ProductService } from './product.service';
export const APIS = [AddressService, CalculationService, CaseService, ConfigurationService, DIPService, DocumentService, FMAService, FirmService, IllustrationService, IntermediaryService, PaymentService, PortalUserService, ProductService];
