/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncomeDetailCompany } from './incomeDetailCompany';


export interface Accountant { 
    company?: IncomeDetailCompany | null;
    email?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    qualification?: string | null;
    telephone?: string | null;
}

