/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type AddressType3 = 'Firm Address' | 'Trading Address';

export const AddressType3 = {
    FirmAddress: 'Firm Address' as AddressType3,
    TradingAddress: 'Trading Address' as AddressType3
};

