/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressAddressType } from './addressAddressType';


export interface Address { 
    addressLine1?: string | null;
    addressLine2?: string | null;
    addressLine3?: string | null;
    addressLine4?: string | null;
    addressLine5?: string | null;
    addressType?: AddressAddressType | null;
    city?: string | null;
    country?: string | null;
    region?: string | null;
    state?: string | null;
    zipCode?: string | null;
}

