/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type AddressType2 = 'Undefined' | 'UK' | 'BFPO' | 'OVERSEAS';

export const AddressType2 = {
    Undefined: 'Undefined' as AddressType2,
    Uk: 'UK' as AddressType2,
    Bfpo: 'BFPO' as AddressType2,
    Overseas: 'OVERSEAS' as AddressType2
};

