/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address2 { 
    numberOrBuilding?: string | null;
    postcode?: string | null;
    city?: string | null;
    country?: string | null;
    lineOne?: string | null;
    lineTwo?: string | null;
    lineThree?: string | null;
    lineFour?: string | null;
    lineFive?: string | null;
}

