/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Applicant2ContactDetails } from './applicant2ContactDetails';
import { Applicant2ApplicantInfo } from './applicant2ApplicantInfo';


export interface Applicant2 { 
    applicantInfo?: Applicant2ApplicantInfo | null;
    contactDetails?: Applicant2ContactDetails | null;
}

