/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactInformationResponse } from './contactInformationResponse';
import { KeyValuePairOfStringAndString } from './keyValuePairOfStringAndString';
import { CaseStatusResponse } from './caseStatusResponse';


export interface CaseDataResponse { 
    amount?: number;
    assigneeId?: string | null;
    caseId: string;
    casePurposeType?: string | null;
    contactsInformation?: Array<ContactInformationResponse> | null;
    created?: string;
    createdBy?: string | null;
    customData?: Array<KeyValuePairOfStringAndString> | null;
    modified?: string;
    modifiedBy?: string | null;
    ownerId?: string | null;
    stage?: string | null;
    status?: string | null;
    statusHistory?: Array<CaseStatusResponse> | null;
    versionNumber?: number | null;
    assigneeFullName?: string | null;
    createdByFullName?: string | null;
    dossierNumber?: string | null;
    totalLoanAmount?: number | null;
}

