/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaseDocument { 
    date?: string | null;
    description?: string | null;
    externalReference?: string | null;
    id?: string | null;
    mimeType?: string | null;
    name?: string | null;
    size?: number | null;
    stage?: string | null;
    status?: string | null;
}

