/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentsSubBuilding } from './componentsSubBuilding';
import { ComponentsBuilding } from './componentsBuilding';
import { ComponentsDeliveryService } from './componentsDeliveryService';
import { ComponentsLocality } from './componentsLocality';
import { ComponentsPostalCode } from './componentsPostalCode';
import { ComponentsStreet } from './componentsStreet';
import { ComponentsOrganization } from './componentsOrganization';
import { ComponentsRouteService } from './componentsRouteService';


export interface Components { 
    language?: string;
    countryName: string;
    countryIso3: string;
    countryIso2?: string | null;
    postalCode?: ComponentsPostalCode | null;
    street?: ComponentsStreet | null;
    secondaryStreet?: ComponentsStreet | null;
    locality?: ComponentsLocality | null;
    physicalLocality?: ComponentsLocality | null;
    building?: ComponentsBuilding | null;
    subBuilding?: ComponentsSubBuilding | null;
    organization?: ComponentsOrganization | null;
    deliveryService?: ComponentsDeliveryService | null;
    secondaryDeliveryService?: ComponentsDeliveryService | null;
    routeService?: ComponentsRouteService | null;
}

