/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocalityRegion } from './localityRegion';
import { Locality } from './locality';
import { LocalityDistrict } from './localityDistrict';
import { LocalityTown } from './localityTown';


/**
 * @type ComponentsLocality
 * @export
 */
export type ComponentsLocality = Locality;

