/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyValuePairOfStringAndString } from './keyValuePairOfStringAndString';


export interface ContactInformationResponse { 
    contactInformationId?: number;
    contactType?: string | null;
    firstName?: string | null;
    familyName?: string | null;
    dateOfBirth?: string | null;
    customData?: Array<KeyValuePairOfStringAndString> | null;
}

