/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanSummary } from './loanSummary';
import { ApplicantDIPSummary } from './applicantDIPSummary';


export interface DipSummaryResponse { 
    applicationDraftId?: number;
    versionNumber?: number;
    applicants?: Array<ApplicantDIPSummary> | null;
    expirationDateTime?: string | null;
    loan?: LoanSummary | null;
    stage?: string | null;
    status?: string | null;
}

