/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExistingMortgageRequestAllOf { 
    amount?: number | null;
    amountToBeRepaid?: number | null;
    continuingBalance?: number | null;
    currentOutstandingBalance?: number | null;
    debtConsolidationConfirmation?: boolean | null;
    estimatedValueOfTheProperty?: number | null;
    existingLender?: string | null;
    expectedRentalIncome?: number | null;
    isPropertyMortgaged?: boolean | null;
    isRepaidOnCompletionOfTheApplication?: boolean | null;
    monthlyPayment?: number | null;
    monthlyRentalIncome?: number | null;
    mortgageAccountNumber?: string | null;
    otherLender?: string | null;
    ownersOfTheProperty?: Array<number> | null;
    propertyIsLet?: boolean | null;
    propertyWillBeLetOnCompletionOfThisApplication?: boolean | null;
    reason?: string | null;
    remainingTermInMonths?: number | null;
    saleOfPropertySupportsARepaymentStrategy?: boolean | null;
    tenancyAgreementIsInPlace?: boolean | null;
}

