/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fee2Basis } from './fee2Basis';
import { FeeUnit } from './feeUnit';


export interface Fee2 { 
    value: number;
    unit: FeeUnit;
    basis?: Fee2Basis | null;
}
export namespace Fee2 {
}


