/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Fee3 { 
    amount?: number | null;
    calculationType?: string | null;
    endDate?: string | null;
    feeType?: string | null;
    isIncludedInDueDateCalculation?: boolean | null;
    isIncludedInOutstanding?: boolean | null;
    percentage?: number | null;
    reference?: string | null;
    startDate?: string | null;
}

