/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeesToBePaid } from './feesToBePaid';
import { LenderFee } from './lenderFee';
import { IntermediaryFee } from './intermediaryFee';


export interface FeePaymentResponseAllOf { 
    feesAddedToLoan?: Array<LenderFee> | null;
    feesToBePaid?: FeesToBePaid | null;
    loanId?: number | null;
    otherFees?: IntermediaryFee | null;
}

