/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LenderFee } from './lenderFee';


export interface FeesToBePaid { 
    areFeesPaid?: boolean;
    lenderFees?: Array<LenderFee> | null;
    productFees?: Array<LenderFee> | null;
}

