/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialIncomeYearEnding } from './financialIncomeYearEnding';


export interface FinancialIncome { 
    annualDrawings?: number | null;
    projectedDividend?: number | null;
    projectedGrossProfit?: number | null;
    projectedNetProfit?: number | null;
    year?: number | null;
    yearEnding?: FinancialIncomeYearEnding | null;
}

