/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressType3 } from './addressType3';


export interface FirmAddressModel { 
    id: string;
    firmId: string;
    addressType: AddressType3;
    numberOrBuilding?: string | null;
    postcode?: string | null;
    city?: string | null;
    country?: string | null;
    lineOne?: string | null;
    lineTwo?: string | null;
    lineThree?: string | null;
    lineFour?: string | null;
    lineFive?: string | null;
    tradingName?: string | null;
    businessDevelopmentManager?: string | null;
    isActive: boolean;
    lastUpdated: string;
    version: number;
}
export namespace FirmAddressModel {
}


