/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FutureChangeInIncome { 
    changeType?: string | null;
    description?: string | null;
    reason?: string | null;
    timeScale?: string | null;
    typeOfChange?: string | null;
}

