/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GlobalPayPaymentResponse { 
    authcode?: string | null;
    result?: string | null;
    message?: string | null;
    pasref?: string | null;
    avspostcoderesult?: string | null;
    avsaddressresult?: string | null;
    cvnresult?: string | null;
    account?: string | null;
    merchanT_ID?: string | null;
    ordeR_ID?: string | null;
    timestamp?: string | null;
    amount?: string | null;
    merchanT_RESPONSE_URL?: string | null;
    pas_uuid?: string | null;
    srd?: string | null;
    shA1HASH?: string | null;
    hpP_CUSTOMER_EMAIL?: string | null;
    hpP_CHALLENGE_REQUEST_INDICATOR?: string | null;
    hpP_ENABLE_EXEMPTION_OPTIMIZATION?: string | null;
    hpP_ADDRESS_MATCH_INDICATOR?: string | null;
    hpP_FRAUDFILTER_RESULT?: string | null;
    batchid?: string | null;
}

