/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FinancialIncome } from './financialIncome';
import { IncomeDetailAccountant } from './incomeDetailAccountant';
import { Income } from './income';
import { IncomeDetailCompany } from './incomeDetailCompany';
import { IncomeDetailCurrentEmploymentStatus } from './incomeDetailCurrentEmploymentStatus';
import { IncomeDetailContact } from './incomeDetailContact';


export interface IncomeDetail { 
    accountant?: IncomeDetailAccountant | null;
    allowances?: { [key: string]: Income; } | null;
    basicSalary?: number | null;
    businessStartDate?: string | null;
    canIncomeBeVerified?: boolean | null;
    company?: IncomeDetailCompany | null;
    contact?: IncomeDetailContact | null;
    contractEndDate?: string | null;
    contractingTotalInMonths?: number | null;
    contractStartDate?: string | null;
    contractTerm?: string | null;
    contractType?: string | null;
    /**
     * ISO 4217 three letter currency code
     */
    currencyCode?: string | null;
    currentEmploymentStatus?: IncomeDetailCurrentEmploymentStatus | null;
    dailyRate?: number | null;
    daysPerWeek?: number | null;
    employer?: IncomeDetailContact | null;
    financialIncomes?: Array<FinancialIncome> | null;
    guaranteedIncome?: { [key: string]: Income; } | null;
    hasGapsBetweenContractsInLast12Months?: boolean | null;
    hourlyRate?: number | null;
    hoursPerWeek?: number | null;
    incomeDetailId?: number | null;
    isApplicantProfessionalProvidingServices?: boolean | null;
    isContractLikelyToBeRenewed?: boolean | null;
    isIncomeRecurrentSalaryOrDailyRate?: string | null;
    isInProbatoryPeriod?: boolean | null;
    isPermanentAtEndOfProbatoryPeriod?: boolean | null;
    jobTitle?: string | null;
    last12MonthsIncome?: number | null;
    last3MonthsIncome?: number | null;
    last6MonthsIncome?: number | null;
    natureOfTheBusiness?: string | null;
    netMonthlyIncome?: number | null;
    nonGuaranteedIncome?: { [key: string]: Income; } | null;
    partnershipType?: string | null;
    probatoryPeriod?: number | null;
    probatoryPeriodEndDate?: string | null;
    reasonForGapsBetweenContracts?: string | null;
    salaryFrequency?: string | null;
    shareOfBusinessOwned?: number | null;
    temporaryContractType?: string | null;
}

