/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type IncomeDetailType = 'Overtime' | 'Bonus' | 'Commission';

export const IncomeDetailType = {
    Overtime: 'Overtime' as IncomeDetailType,
    Bonus: 'Bonus' as IncomeDetailType,
    Commission: 'Commission' as IncomeDetailType
};

