/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntermediarySummary } from './intermediarySummary';


export interface IntermediarySearchResponse { 
    intermediaries?: Array<IntermediarySummary> | null;
    page?: number;
    size?: number;
    total?: number;
    totalPages?: number;
}

