/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type IntermediaryRole = 'Supervisor' | 'Advisor' | 'Assistant' | 'Viewer' | 'LenderAdvisorAdmin' | 'LenderAdvisorSupport' | 'LenderAdvisorViewer' | 'SupervisorAndAdvisor' | 'SupervisorAndAssistant';

export const IntermediaryRole = {
    Supervisor: 'Supervisor' as IntermediaryRole,
    Advisor: 'Advisor' as IntermediaryRole,
    Assistant: 'Assistant' as IntermediaryRole,
    Viewer: 'Viewer' as IntermediaryRole,
    LenderAdvisorAdmin: 'LenderAdvisorAdmin' as IntermediaryRole,
    LenderAdvisorSupport: 'LenderAdvisorSupport' as IntermediaryRole,
    LenderAdvisorViewer: 'LenderAdvisorViewer' as IntermediaryRole,
    SupervisorAndAdvisor: 'SupervisorAndAdvisor' as IntermediaryRole,
    SupervisorAndAssistant: 'SupervisorAndAssistant' as IntermediaryRole
};

