/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductAvailabilityResponse } from './productAvailabilityResponse';


export interface LoanProductAvailabilityResponse { 
    applicationDraftId?: number;
    feesAddedToLoan?: number | null;
    loanAmount?: number | null;
    loanId?: number;
    ltv?: number;
    productAvailability?: Array<ProductAvailabilityResponse> | null;
    propertyPurchasePrice?: number | null;
    totalLoanAmount?: number | null;
}

