/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanProduct2ProductDetails } from './loanProduct2ProductDetails';
import { EarlyRepaymentCharge } from './earlyRepaymentCharge';


export interface LoanProduct2 { 
    aprc?: number;
    baseProductCode?: string | null;
    durationInMonths?: number | null;
    earlyRepaymentCharges?: Array<EarlyRepaymentCharge> | null;
    features?: Array<string> | null;
    freeTariffCriterionTypeCdList?: Array<number> | null;
    initialRate?: number | null;
    monthlyPayment?: number;
    productCode?: string | null;
    productDetails?: LoanProduct2ProductDetails | null;
    productFee?: number;
    productName?: string | null;
    termYear?: number;
    variabilityType?: string | null;
}

