/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RejectionReasonResponse } from './rejectionReasonResponse';


export interface LoanStateResponse2 { 
    changeDate?: string;
    createdBy?: string | null;
    documentId?: string | null;
    dossierNumber?: string | null;
    externalReference?: string | null;
    loanId?: number | null;
    stage?: string | null;
    status?: string | null;
    traceId?: string | null;
    rejectionReasons?: Array<RejectionReasonResponse> | null;
}

