/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoanPartSummary { 
    loanAmount?: number | null;
    productCode?: string | null;
    productName?: string | null;
    term?: string | null;
    type?: string | null;
    loanPartType?: string | null;
}

