/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDetails } from './productDetails';
import { PrepaymentPenaltyTier } from './prepaymentPenaltyTier';
import { Fee3 } from './fee3';


/**
 * @type LoanProduct2ProductDetails
 * @export
 */
export type LoanProduct2ProductDetails = ProductDetails;

