/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type PermissionType = 'View' | 'Illustration' | 'DecisionInPrinciple' | 'FullMortgageApplication';

export const PermissionType = {
    View: 'View' as PermissionType,
    Illustration: 'Illustration' as PermissionType,
    DecisionInPrinciple: 'DecisionInPrinciple' as PermissionType,
    FullMortgageApplication: 'FullMortgageApplication' as PermissionType
};

