/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PortalIntermediaryRole =
  | 'Supervisor'
  | 'Advisor'
  | 'Assistant'
  | 'Viewer'
  | 'LenderAdvisorAdmin'
  | 'LenderAdvisorSupport'
  | 'SupervisorAndAdvisor'
  | 'SupervisorAndAssistant'
  | 'LenderAdvisorViewer';

export const PortalIntermediaryRole = {
  Supervisor: 'Supervisor' as PortalIntermediaryRole,
  Advisor: 'Advisor' as PortalIntermediaryRole,
  Assistant: 'Assistant' as PortalIntermediaryRole,
  Viewer: 'Viewer' as PortalIntermediaryRole,
  LenderAdvisorAdmin: 'LenderAdvisorAdmin' as PortalIntermediaryRole,
  LenderAdvisorSupport: 'LenderAdvisorSupport' as PortalIntermediaryRole,
  SupervisorAndAdvisor: 'SupervisorAndAdvisor' as PortalIntermediaryRole,
  SupervisorAndAssistant: 'SupervisorAndAssistant' as PortalIntermediaryRole,
  LenderAdvisorViewer: 'LenderAdvisorViewer' as PortalIntermediaryRole,
};
