/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LoanPart } from './loanPart';


export interface ProductSelectionResponseAllOf { 
    feesAddedToLoan?: number | null;
    loanAmount?: number | null;
    loanParts?: Array<LoanPart> | null;
    ltv?: number;
    mortgageClub?: string | null;
    network?: string | null;
    propertyValuationAmount?: number | null;
    purchaseAmount?: number | null;
    totalLoanAmount?: number | null;
    useMortgageClub?: boolean | null;
    valuationType?: string | null;
}

