/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductAvailabilityResponse { 
    loanPartAmount?: number;
    loanPartId?: number;
    productCode?: string | null;
    productType?: string | null;
    reasons?: Array<string> | null;
    status?: string | null;
    tomMonths?: number;
    tomYears?: number;
}

