/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PropertyAndLoanDetailsRequest { 
    versionNumber?: number;
    applicantsLiveInTheProperty?: boolean | null;
    fullMarketValue?: number | null;
    hasCustomerFoundProperty?: boolean | null;
    isPurchaseFromFamily?: boolean | null;
    loanAmount?: number | null;
    propertyLocation?: string | null;
    propertyOwnershipType?: string | null;
    purchasePrice?: number | null;
}

