/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type ResponseType = 'Error' | 'Warning' | 'Information';

export const ResponseType = {
    Error: 'Error' as ResponseType,
    Warning: 'Warning' as ResponseType,
    Information: 'Information' as ResponseType
};

