/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RetirementIncomeDetail { 
    anticipatedAnnualIncome?: number | null;
    anticipatedNetMonthlyIncome?: number | null;
    canTheIncomeBeVerified?: boolean | null;
    currentValue?: number | null;
    description?: string | null;
    incomeSource?: string | null;
    initialDrawdownAmount?: number | null;
    isTheIncomeGuaranteed?: boolean | null;
    pensionType?: string | null;
    projectedValue?: number | null;
    startDate?: string | null;
}

