/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type Stage = 'New' | 'Draft' | 'Illustration' | 'DIP' | 'FMA' | 'Underwriting';

export const Stage = {
    New: 'New' as Stage,
    Draft: 'Draft' as Stage,
    Illustration: 'Illustration' as Stage,
    Dip: 'DIP' as Stage,
    Fma: 'FMA' as Stage,
    Underwriting: 'Underwriting' as Stage
};

