/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type Status = 'Active' | 'InProgress' | 'Completed' | 'Submitted' | 'Assessment' | 'Rejected' | 'Declined' | 'Cancelled';

export const Status = {
    Active: 'Active' as Status,
    InProgress: 'InProgress' as Status,
    Completed: 'Completed' as Status,
    Submitted: 'Submitted' as Status,
    Assessment: 'Assessment' as Status,
    Rejected: 'Rejected' as Status,
    Declined: 'Declined' as Status,
    Cancelled: 'Cancelled' as Status
};

