/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StipulationDocument { 
    date?: string | null;
    documentName?: string | null;
    rejectionReasons?: Array<string> | null;
    status?: string | null;
    stipulationDescription?: string | null;
    stipulationId?: string | null;
    stipulationType?: string | null;
}

