/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FirmType } from './firmType';
import { SubmissionRoute } from './submissionRoute';


export interface SubmissionRouteAssociationModelEx { 
    firmId: string;
    networks?: Array<SubmissionRoute>;
    clubs?: Array<SubmissionRoute>;
    directlyAuthorized?: Array<SubmissionRoute>;
    firmType?: FirmType | null;
    firmName?: string | null;
    fcaReference?: number | null;
}

