/**
 * Broker Portal API
 * A Microservice API to support request from the front-end broker portals.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactDetails } from './contactDetails';


export interface ValuationDetailsRequest { 
    versionNumber?: number;
    additionalInformationForValuer?: string | null;
    applicantId?: number | null;
    companyName?: string | null;
    contactInformation?: ContactDetails | null;
    contactName?: string | null;
    valuationContact?: string | null;
}

