export enum ApplicantsType {
  FIRST_TIME_BUYER = 'FIRST_TIME_BUYER',
  EXISTING_CUSTOMER = 'EXISTING_CUSTOMER',
  BORROWER_WITH_OTHER_LENDER = 'BORROWER_WITH_OTHER_LENDER',
  OWNER_WITH_NO_MORTGAGE = 'OWNER_WITH_NO_MORTGAGE',
}
