export enum ConstructionType {
  BRICK_STONE = 'BRICK_STONE',
  CONCRETE = 'CONCRETE',
  STEEL_FRAMED = 'STEEL_FRAMED',
  MODERN_TIMBER_FRAMED = 'MODERN_TIMBER_FRAMED',
  MODERN_METHOD_OF_CONSTRUCTION_MMC_SYSTEM_BUILT = 'MODERN_METHOD_OF_CONSTRUCTION_MMC_SYSTEM_BUILT',
  LARGE_PANEL_SYSTEM = 'LARGE_PANEL_SYSTEM',
  OTHER = 'OTHER',
}
