export enum DepositType {
  SAVINGS = 'SAVINGS',
  EQUITY_RELEASE = 'EQUITY_RELEASE',
  GIFT = 'GIFT',
  FORCES_HELP_TO_BUY_SCHEME = 'FORCES_HELP_TO_BUY_SCHEME',
  HELP_TO_BUY_ISA_SCHEME = 'HELP_TO_BUY_ISA_SCHEME',
  INHERITANCE = 'INHERITANCE',
}
