export enum EmploymentStatus {
  EMPLOYED = 'EMPLOYED',
  SELF_EMPLOYED_PARTNERSHIP = 'SELF_EMPLOYED_PARTNERSHIP',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  DIRECTOR_25_PLUS = 'DIRECTOR_25_PLUS',
  DIRECTOR_LESS_25 = 'DIRECTOR_LESS_25',
  HOME_MAKER = 'HOME_MAKER',
  STUDENT = 'STUDENT',
  NOT_EMPLOYED = 'NOT_EMPLOYED',
  RETIRED = 'RETIRED',
}
