export enum LoanStatus {
  Active = 'ACTIVE',
  InProgress = 'IN_PROGRESS',
  Completed = 'COMPLETED',
  Submitted = 'SUBMITTED',
  Assessment = 'ASSESSMENT',
  Rejected = 'REJECTED',
  Cancelled = 'CANCELLED',
  Promoting = 'PROMOTING',
  Referred = 'REFERRED',
  Accepted = 'ACCEPTED',
  Documentation = 'DOCUMENTATION',
  UnderwritingInProgress = 'UNDERWRITING_IN_PROGRESS',
  UnderwritingAccepted = 'UNDERWRITING_ACCEPTED',
  UnderwritingApproved = 'UNDERWRITING_APPROVED',
  AdditionalDocumentation = 'ADDITIONAL_DOCUMENTATION',
  ValuationPerformed = 'VALUATION_PERFORMED',
  Undefined = 'UNDEFINED',
}
