export enum PropertyStyle {
  SEMI_DETACHED = 'SEMI_DETACHED',
  DETACHED = 'DETACHED',
  END_TERRACE = 'END_TERRACE',
  MID_TERRACE = 'MID_TERRACE',
  PURPOSE_BUILT_APARTMENT = 'PURPOSE_BUILT_APARTMENT',
  CONVERTED_APARTMENT = 'CONVERTED_APARTMENT',
  OTHER = 'OTHER',
}
