export enum RetirementIncomeSource {
  PENSION_WAR_PENSION_SCHEME = 'PENSION_WAR_PENSION_SCHEME',
  PENSION_INCOME = 'PENSION_INCOME',
  PENSION_STATE = 'PENSION_STATE',
  INVESTMENT_INCOME = 'INVESTMENT_INCOME',
  OTHER_INCOME = 'OTHER_INCOME',
}
