export enum ValuationType {
  UNDEFINED = 'UNDEFINED',
  FREE_VALUATION = 'FREE_VALUATION',
  BASIC_VALUATION = 'BASIC_VALUATION',
  HOME_BUYERS_REPORT = 'HOME_BUYERS_REPORT',
  FULL_SURVEY = 'FULL_SURVEY',
}
