export * from './address.service';
import { AddressService } from './address.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './firms.service';
import { FirmsService } from './firms.service';
export * from './intermediary.service';
import { IntermediaryService } from './intermediary.service';
export * from './lender.service';
import { LenderService } from './lender.service';
export * from './lenderUsers.service';
import { LenderUsersService } from './lenderUsers.service';
export * from './portalUser.service';
import { PortalUserService } from './portalUser.service';
export * from './procurationFees.service';
import { ProcurationFeesService } from './procurationFees.service';
export * from './submissionRoutes.service';
import { SubmissionRoutesService } from './submissionRoutes.service';
export const APIS = [AddressService, ConfigurationService, FirmsService, IntermediaryService, LenderService, LenderUsersService, PortalUserService, ProcurationFeesService, SubmissionRoutesService];
