export const mockFirm = {
  firmType: 'DirectlyAuthorized',
  firmName: 'testName',
  fcaReference: 802030,
  principalFcaReference: 0,
  reference: 'test',
  email: 'test@test.com',
  telephone: '',
  website: 'www.test.com',
  complaintsWebpage: 'http://test.com',
  isActive: false,
  isInReview: false,
  numberOrBuilding: 'test',
  address: {
    postcode: 'BH1 1LG',
    city: 'Barcelona',
    country: 'Spain',
    lineOne: 'lineOne',
    lineTwo: 'lineTwo',
    lineThree: 'lineThree',
    lineFour: 'lineFour',
    lineFive: 'lineFive',
  },
  tradingName: 'test',
  businessDevelopmentManager: 'test',
  isTradingAddress: false,
};
