/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type AddressType = 'UnitedKingdom' | 'Overseas' | 'BritishForcesPostOffice' | 'Manual';

export const AddressType = {
    UnitedKingdom: 'UnitedKingdom' as AddressType,
    Overseas: 'Overseas' as AddressType,
    BritishForcesPostOffice: 'BritishForcesPostOffice' as AddressType,
    Manual: 'Manual' as AddressType
};

