/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressModelComponents } from './addressModelComponents';
import { LocationModel } from './locationModel';


export interface AddressModel { 
    postalCode: string;
    location: LocationModel;
    region?: string | null;
    lineOne?: string | null;
    lineTwo?: string | null;
    lineThree?: string | null;
    lineFour?: string | null;
    lineFive?: string | null;
    lineSix?: string | null;
    components?: AddressModelComponents | null;
}

