/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Components } from './components';
import { ComponentsSubBuilding } from './componentsSubBuilding';
import { ComponentsBuilding } from './componentsBuilding';
import { ComponentsDeliveryService } from './componentsDeliveryService';
import { ComponentsLocality } from './componentsLocality';
import { ComponentsPostalCode } from './componentsPostalCode';
import { ComponentsStreet } from './componentsStreet';
import { ComponentsOrganization } from './componentsOrganization';
import { ComponentsRouteService } from './componentsRouteService';


/**
 * @type AddressModelComponents
 * @export
 */
export type AddressModelComponents = Components;

