/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FirmType } from './firmType';


export interface FirmSearchResultEntry { 
    id: string;
    firmType: FirmType;
    firmName: string;
    fcaReference: number;
    reference?: string | null;
    isActive: boolean;
    isInReview: boolean;
}
export namespace FirmSearchResultEntry {
}


