/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressType2 } from './addressType2';


export interface FirmAddressModelEx { 
    addressType?: AddressType2;
    businessDevelopmentManager?: string | null;
    city?: string | null;
    country?: string | null;
    firmId?: string | null;
    id?: string | null;
    intermediaryIds?: Array<string>;
    isActive?: boolean;
    lastUpdated?: string;
    lineFive?: string | null;
    lineFour?: string | null;
    lineOne?: string | null;
    lineThree?: string | null;
    lineTwo?: string | null;
    numberOrBuilding?: string | null;
    postcode?: string | null;
    tradingName?: string | null;
    version?: number;
}
export namespace FirmAddressModelEx {
}


