/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { IntermediaryModelProfilePicture } from './intermediaryModelProfilePicture';
import { IntermediaryStatus } from './intermediaryStatus';
import { Telephone } from './telephone';
import { Person } from './person';


export interface IntermediaryModel { 
    intermediaryId: string;
    subordinateIntermediaryIds?: Array<string>;
    advisorUniqueId?: string | null;
    firmId: string;
    roleMappings: { [key: string]: Role; };
    person: Person;
    tradingAddressId: string;
    email: string;
    telephone: Telephone;
    fcaStatus?: string | null;
    profilePicture?: IntermediaryModelProfilePicture | null;
    copyCaseNotificationsToAdminAssistants?: boolean;
    receiveMarketingMaterials?: boolean;
    agreeToTermsAndConditions?: boolean;
    status: IntermediaryStatus;
    isInReview?: boolean;
    lastUpdated: string;
    creationDate: string;
    firstActivationDate?: string | null;
    version: number;
}
export namespace IntermediaryModel {
}


