/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntermediaryModelProfilePicture } from './intermediaryModelProfilePicture';
import { PanelPermissionType } from './panelPermissionType';
import { FirmFcaDetailsModelTelephone } from './firmFcaDetailsModelTelephone';
import { IntermediaryStatus } from './intermediaryStatus';
import { IntermediaryRole } from './intermediaryRole';
import { IntermediaryResponsePerson } from './intermediaryResponsePerson';
import { IntermediarySummary } from './intermediarySummary';


export interface IntermediaryResponse { 
    advisorUniqueId?: string | null;
    agreeToTermsAndConditions?: boolean;
    copyCaseNotificationsToAdminAssistants?: boolean;
    creationDate?: string;
    email?: string | null;
    fcaStatus?: string | null;
    firmId?: string | null;
    firstActivationDate?: string | null;
    intermediaryId?: string | null;
    intermediaryRole?: IntermediaryRole;
    isInReview?: boolean;
    lastUpdated?: string;
    permissionType?: PanelPermissionType;
    person?: IntermediaryResponsePerson | null;
    profilePicture?: IntermediaryModelProfilePicture | null;
    receiveMarketingMaterials?: boolean;
    roleMappings?: Array<IntermediarySummary> | null;
    status?: IntermediaryStatus;
    subordinateIntermediaries?: Array<IntermediarySummary> | null;
    telephone?: FirmFcaDetailsModelTelephone | null;
    tradingAddressId?: string | null;
    version?: number;
}
export namespace IntermediaryResponse {
}


