/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntermediaryStatus } from './intermediaryStatus';
import { IntermediaryRole } from './intermediaryRole';
import { Person } from './person';


export interface IntermediarySearchResultEntry { 
    id: string;
    firmId: string;
    person: Person;
    advisorUniqueId?: string | null;
    position: IntermediaryRole;
    email: string;
    status: IntermediaryStatus;
    isInReview: boolean;
}
export namespace IntermediarySearchResultEntry {
}


