/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntermediaryRole } from './intermediaryRole';
import { Telephone } from './telephone';
import { Person } from './person';


export interface InviteIntermediaryRequest { 
    firmId: string;
    advisorUniqueId?: string | null;
    intermediaryRole: IntermediaryRole;
    person: Person;
    tradingAddressId: string;
    email: string;
    telephone: Telephone;
    copyCaseNotificationsToAdminAssistants?: boolean;
}
export namespace InviteIntermediaryRequest {
}


