/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PanelPermissionType } from './panelPermissionType';
import { IntermediaryRole } from './intermediaryRole';
import { IntermediarySummary } from './intermediarySummary';


export interface LenderUserResponseAllOf { 
    permissionType?: PanelPermissionType;
    role?: IntermediaryRole;
    roleMappings?: Array<IntermediarySummary> | null;
}
export namespace LenderUserResponseAllOf {
}


