/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PanelPermissions { 
    assistants?: Array<string> | null;
    configuration?: Array<string> | null;
    firms?: Array<string> | null;
    intermediaries?: Array<string> | null;
    portal?: Array<string> | null;
    profiles?: Array<string> | null;
    submissionRoutes?: Array<string> | null;
    switcher?: Array<string> | null;
    lender?: Array<string> | null;
}

