/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PanelIntermediaryRole =
  | 'Supervisor'
  | 'Advisor'
  | 'Assistant'
  | 'Viewer'
  | 'LenderAdvisorAdmin'
  | 'LenderAdvisorSupport'
  | 'SupervisorAndAdvisor'
  | 'SupervisorAndAssistant'
  | 'LenderAdvisorViewer';

export const PanelIntermediaryRole = {
  Supervisor: 'Supervisor' as PanelIntermediaryRole,
  Advisor: 'Advisor' as PanelIntermediaryRole,
  Assistant: 'Assistant' as PanelIntermediaryRole,
  Viewer: 'Viewer' as PanelIntermediaryRole,
  LenderAdvisorAdmin: 'LenderAdvisorAdmin' as PanelIntermediaryRole,
  LenderAdvisorSupport: 'LenderAdvisorSupport' as PanelIntermediaryRole,
  SupervisorAndAdvisor: 'SupervisorAndAdvisor' as PanelIntermediaryRole,
  SupervisorAndAssistant: 'SupervisorAndAssistant' as PanelIntermediaryRole,
  LenderAdvisorViewer: 'LenderAdvisorViewer' as PanelIntermediaryRole,
};
