/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TrailFee2Basis } from './trailFee2Basis';
import { TrailFee2 } from './trailFee2';
import { EndingType } from './endingType';
import { FeeUnit } from './feeUnit';


/**
 * @type ProcurationFeeModel2TrailFee
 * @export
 */
export type ProcurationFeeModel2TrailFee = TrailFee2;

