/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationType } from './applicationType';
import { Fee } from './fee';
import { TrailFee } from './trailFee';
import { SubmissionRouteType } from './submissionRouteType';


export interface ProcurationFeeModel { 
    applicationType: ApplicationType;
    submissionRouteType: SubmissionRouteType;
    completionFee: Fee;
    trailFee?: TrailFee | null;
}
export namespace ProcurationFeeModel {
}


