/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterNewFirmAddressRequest { 
    numberOrBuilding?: string | null;
    postcode?: string | null;
    city?: string | null;
    country?: string | null;
    lineOne?: string | null;
    lineTwo?: string | null;
    lineThree?: string | null;
    lineFour?: string | null;
    lineFive?: string | null;
    tradingName?: string | null;
    businessDevelopmentManager?: string | null;
    isTradingAddress?: boolean;
    isActive?: boolean;
}

