/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterNewUserRequestUserType } from './registerNewUserRequestUserType';
import { Telephone } from './telephone';
import { PermissionType } from './permissionType';
import { UserRole } from './userRole';
import { Person } from './person';
import { ProfilePicture } from './profilePicture';


export interface RegisterNewUserRequest { 
    userId?: string | null;
    person: Person;
    userType: RegisterNewUserRequestUserType;
    userRole: UserRole;
    permissionType: PermissionType;
    email: string;
    telephone?: Telephone;
    profilePicture?: ProfilePicture;
    agreeToTermsAndConditions?: boolean;
    receiveMarketingMaterials?: boolean;
}
export namespace RegisterNewUserRequest {
}


