/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntermediaryStatus } from './intermediaryStatus';
import { IntermediaryRole } from './intermediaryRole';
import { SearchFirmDetailsRequestFirmNameSortOrder } from './searchFirmDetailsRequestFirmNameSortOrder';


export interface SearchIntermediariesRequest { 
    partialName?: string | null;
    partialAdvisorUniqueId?: string | null;
    position?: Array<IntermediaryRole> | null;
    partialEmail?: string | null;
    status?: Array<IntermediaryStatus> | null;
    isInReview?: boolean | null;
    nameSortOrder?: SearchFirmDetailsRequestFirmNameSortOrder | null;
}

