/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchFirmDetailsRequestFirmType } from './searchFirmDetailsRequestFirmType';
import { SearchFirmDetailsRequestFirmNameSortOrder } from './searchFirmDetailsRequestFirmNameSortOrder';


export interface SearchFirmDetailsRequest { 
    partialFirmName?: string | null;
    fcaReference?: number | null;
    principalFcaReference?: number | null;
    partialReference?: string | null;
    isActive?: boolean | null;
    isInReview?: boolean | null;
    firmType?: SearchFirmDetailsRequestFirmType | null;
    firmNameSortOrder?: SearchFirmDetailsRequestFirmNameSortOrder | null;
}

