/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SelfRegistrationPermissionType } from './selfRegistrationPermissionType';
import { SelfRegistrationType } from './selfRegistrationType';


export interface SelfRegistrationSettings { 
    registrationType: SelfRegistrationType;
    registrationPermissionType: SelfRegistrationPermissionType;
    qualifiedDomain?: string | null;
}
export namespace SelfRegistrationSettings {
}


