/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmissionRouteType } from './submissionRouteType';


export interface SubmissionRouteSearchResultEntry { 
    id: string;
    firmName: string;
    firmFcaReference: number;
    reference?: string | null;
    submissionRouteType: SubmissionRouteType;
    isActivated: boolean;
    isInReview: boolean;
}
export namespace SubmissionRouteSearchResultEntry {
}


