/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateUserRequestUserType } from './updateUserRequestUserType';
import { Telephone } from './telephone';
import { PermissionType } from './permissionType';
import { UserRole } from './userRole';
import { Person } from './person';
import { UserStatus } from './userStatus';
import { ProfilePicture } from './profilePicture';


export interface UpdateUserRequest { 
    person: Person;
    userType: UpdateUserRequestUserType;
    status: UserStatus;
    userRole: UserRole;
    permissionType: PermissionType;
    email: string;
    telephone?: Telephone;
    profilePicture?: ProfilePicture;
    agreeToTermsAndConditions?: boolean;
    receiveMarketingMaterials?: boolean;
    version: number;
}
export namespace UpdateUserRequest {
}


