/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FirmFcaDetailsModelTelephone } from './firmFcaDetailsModelTelephone';
import { FirmDetailsModelSelfRegistrationSettings } from './firmDetailsModelSelfRegistrationSettings';
import { FirmType } from './firmType';


export interface UpdateFirmDetailsRequest { 
    firmType: FirmType;
    firmName: string;
    fcaReference: number;
    principalFcaReference?: number | null;
    fcaStatus?: string | null;
    fcaPermissionCode?: string | null;
    reference?: string | null;
    email?: string | null;
    telephone?: FirmFcaDetailsModelTelephone | null;
    website?: string | null;
    complaintsWebpage?: string | null;
    selfRegistrationSettings?: FirmDetailsModelSelfRegistrationSettings | null;
    isActive: boolean;
    isInReview: boolean;
    sendCaseToEmail: boolean;
    version: number;
}
export namespace UpdateFirmDetailsRequest {
}


