/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileResponseAccountInformation } from './userProfileResponseAccountInformation';
import { UserProfileResponsePersonalDetails } from './userProfileResponsePersonalDetails';
import { FirmAddressModel } from './firmAddressModel';


export interface UserProfileResponse { 
    advisorUniqueId?: string | null;
    personalDetails?: UserProfileResponsePersonalDetails | null;
    accountInformation?: UserProfileResponseAccountInformation | null;
    tradingAddressId?: string | null;
    tradingAddresses?: Array<FirmAddressModel> | null;
    agreeToTermsAndConditions?: boolean;
    receiveMarketingMaterials?: boolean;
    version?: number;
}

