/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type UserRole = 'Supervisor' | 'Advisor' | 'Assistant' | 'Viewer' | 'LenderAdvisorAdmin' | 'LenderAdvisorSupport' | 'LenderAdvisorViewer' | 'SupervisorAndAdvisor' | 'SupervisorAndAssistant';

export const UserRole = {
    Supervisor: 'Supervisor' as UserRole,
    Advisor: 'Advisor' as UserRole,
    Assistant: 'Assistant' as UserRole,
    Viewer: 'Viewer' as UserRole,
    LenderAdvisorAdmin: 'LenderAdvisorAdmin' as UserRole,
    LenderAdvisorSupport: 'LenderAdvisorSupport' as UserRole,
    LenderAdvisorViewer: 'LenderAdvisorViewer' as UserRole,
    SupervisorAndAdvisor: 'SupervisorAndAdvisor' as UserRole,
    SupervisorAndAssistant: 'SupervisorAndAssistant' as UserRole
};

