/**
 * Broker Panel API
 * A Microservice API to support request from the front-end broker panel.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 */
export type UserStatus = 'Pending' | 'Active' | 'Inactive';

export const UserStatus = {
    Pending: 'Pending' as UserStatus,
    Active: 'Active' as UserStatus,
    Inactive: 'Inactive' as UserStatus
};

